# This is a basic workflow to help you get started with Actions

name: CD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  CD:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # Use this repository

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Make directory for zip
        run: mkdir deploy

      - name: Copy src folder
        run: cp -r ./sharkle/ ./deploy/

      - name: Copy appspec.yml
        run: cp ./scripts/appspec.yml ./deploy/

      - name: Copy start.sh
        run: cp ./scripts/start.sh ./deploy/

      - name: Zip build folder
        run: zip -r -qq ./sharkle-deploy.zip ./deploy

      - name: Copy zip file to AWS S3
        run: |
          aws s3 cp \
          --region ${{ secrets.AWS_REGION }} \
          --acl private \
          ./sharkle-deploy.zip s3://${{ secrets.AWS_BUCKET }}/

      - name: Create CodeDeploy Deployment
        id: deploy
        run: |
          aws deploy create-deployment \
          --application-name sharkle-deploy \
          --deployment-group-name sharkle-deploy-group \
          --deployment-config-name CodeDeployDefault.OneAtATime \
          --file-exists-behavior OVERWRITE \
          --s3-location bucket=${{ secrets.AWS_BUCKET }},bundleType=zip,key=sharkle-deploy.zip \
          --region ${{ secrets.AWS_REGION }}
