name: Django CI

on:
  push

jobs:
  build:

    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
            MYSQL_DATABASE: 'sharkle_test'
            MYSQL_USER: 'sharkle-test'
            MYSQL_PASSWORD: 'seminar'
            MYSQL_ROOT_PASSWORD: password
        ports:
            - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    strategy:
      max-parallel: 4

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: 3.8.10    
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      working-directory: ./sharkle
    - name: Run Tests
      run: |
        python manage.py test
      env:
          SYSTEM_ENV: GITHUB_WORKFLOW
          SECRET_KEY: '#20i1gz6%r9ri94hv^f(kz*%o80@x!anpp%qcc_+k&s^*63n1$' #Auto generated seceret key, doesn't have any mean
          DB_USER: 'root'
          DB_PASSWORD: 'password'
          DB_HOST: '127.0.0.1'
          
          AWS_S3_ACCESS_KEY_ID: 'Wow'
          AWS_S3_SECRET_ACCESS_KEY: 'Very Good'
          AWS_STORAGE_BUCKET_NAME: 'and this'
          AWS_S3_SIGNATURE_VERSION: 'contains'
          AWS_S3_REGION_NAME: 'seoul'
          DEFAULT_FILE_STORAGE: 'national university'
      working-directory: ./sharkle
